'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Time_Tracker

    '''<summary>
    '''panel_time_tracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_time_tracker As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_employee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''botao_excluir_colaborador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_excluir_colaborador As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''drop_job control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_job As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_activity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_activity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_group As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''radio_filtro_datas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_datas As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''radio_filtro_signed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_signed As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_inicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_final As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_listar_tarefas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_listar_tarefas As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''botao_signoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_signoff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''botao_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_excel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''label_horas_totais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_horas_totais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_horas_totais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_totais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdv_time_tracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_time_tracker As Global.System.Web.UI.WebControls.GridView
End Class
