'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Time_Entry
    
    '''<summary>
    '''drop_opcao_gerencia_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_opcao_gerencia_os As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''botao_opcao_time_entry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_opcao_time_entry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''panel_insere_horas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_insere_horas As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drop_job_insere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_job_insere As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_activity_insere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_activity_insere As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_description_insere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_description_insere As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_hours_insere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_hours_insere As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''caixa_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_calendario_insere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_insere As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calendario_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendario_filtro As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''caixa_machine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_machine As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_group As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_employee As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_salvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_salvar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''label_preencha_campos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_preencha_campos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''panel_busca_horas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca_horas As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drop_job_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_job_busca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_activity_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_activity_busca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''radio_filtro_datas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_datas As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''label_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_inicial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''botao_calendario_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_inicial As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''label_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_final As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''botao_calendario_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_final As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calendario_filtro_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendario_filtro_busca As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''botao_listar_tarefas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_listar_tarefas As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_gera_relatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_gera_relatorio As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''gdv_time_entry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_time_entry As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''label_horas_totais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_horas_totais As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''caixa_horas_totais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_totais As Global.System.Web.UI.WebControls.TextBox
End Class
