'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reservados

    '''<summary>
    '''panel_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''check_filtro_avancado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_filtro_avancado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProducts As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlProducts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProducts1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ck_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_date As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_inicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''label_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_final As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
End Class
