'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class insere_fornecedor

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''botao_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_fecha As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''painel_cadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_cadastro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''caixa_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_fornecedor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_endereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_endereco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_contato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_contato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_telefone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_cnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cnpj As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_ie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_ie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_cadastra_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_cadastra_fornecedor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''label_preencha_campos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_preencha_campos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''painel_cadastro0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_cadastro0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlfornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlfornecedor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdvfornecedores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvfornecedores As Global.System.Web.UI.WebControls.GridView
End Class
