'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class form_impressao_ro
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''imagem_ak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagem_ak As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imagem_isa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagem_isa As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''painel_ro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_ro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ck_orcamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_orcamento As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''caixa_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_fornecedor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_requisitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_requisitante As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_contato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_contato As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_os As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_cod_ref1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_cod_ref1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''label_cod_ref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_cod_ref As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drop_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_telefone As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_observacoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_observacoes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_email As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''label_verba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_verba As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''caixa_verba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_verba As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''label_total_sem_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total_sem_ipi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''currency_drop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_drop As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_total_sem_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_sem_ipi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''access_recupera_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_recupera_os As Global.System.Web.UI.WebControls.AccessDataSource
    
    '''<summary>
    '''access_dados_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_dados_os As Global.System.Web.UI.WebControls.AccessDataSource
End Class
