'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class form_impressao_req
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''imagem_ak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagem_ak As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imagem_isa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagem_isa As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''painel_rc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_rc As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ck_compra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_compra As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ck_copia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_copia As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''caixa_pc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_pc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_fornecedor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_data_emissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_emissao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_endereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_endereco As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_data_entrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_entrega As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_contato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_contato As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_requisitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_requisitante As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_telefone As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_os As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_cod_ref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_cod_ref As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drop_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_email As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_cond_pag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cond_pag As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_cnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cnpj As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_ie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_ie As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''label_total_sem_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total_sem_ipi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''caixa_total_sem_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_sem_ipi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_total_do_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total_do_ipi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''caixa_total_do_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_do_ipi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_total_com_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total_com_ipi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''currency_drop1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_drop1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_total_com_ipi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_com_ipi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''access_recupera_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_recupera_fornecedor As Global.System.Web.UI.WebControls.AccessDataSource
    
    '''<summary>
    '''access_dados_fornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_dados_fornecedor As Global.System.Web.UI.WebControls.AccessDataSource
End Class
