'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class gera_req

    '''<summary>
    '''drop_opcao_gera_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_opcao_gera_req As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''botao_opcao_gera_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_opcao_gera_req As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''botao_busca_itens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_busca_itens As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''botao_gera_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_gera_req As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''button_load control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_load As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_gera_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_gera_req As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panel_opcoes_gera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_opcoes_gera As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''radio_tipo_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_tipo_req As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''botao_grava_req1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_grava_req1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''botao_limpa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_limpa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''drop_os_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_req As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''label_sel_os_gera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_sel_os_gera As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drop_cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cliente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_cliente_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cliente_final As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''radio_razao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_razao As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''label_selecione_razao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_selecione_razao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_tabela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_tabela As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radio_req_orc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_req_orc As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''panel_busca_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca_req As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_os_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''label_sel_os_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_sel_os_busca As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_grava_req control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_grava_req As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''listbox_cod_ref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listbox_cod_ref As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''botao_busca_ref_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_busca_ref_os As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''caixa_cod_ref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cod_ref As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_busca_ref_cod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_busca_ref_cod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_filtro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_fabricantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_fabricantes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_fabricante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_fabricante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_filtro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''botao_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_excel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_requisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_requisita As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''caixa_qtde_requisitar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_qtde_requisitar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_retira_estoque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_retira_estoque As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''label_item_selecionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_item_selecionado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_sel_os_requisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_sel_os_requisita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''access_rec_cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_rec_cliente As Global.System.Web.UI.WebControls.AccessDataSource
End Class
