'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class adm_despesas

    '''<summary>
    '''drop_opcao_adm_desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_opcao_adm_desp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''botao_opcao_gerencia_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_opcao_gerencia_nota As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_insere_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_insere_despesa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_os_lanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_lanca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cliente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_cliente_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cliente_final As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_valor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_valor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drop_despesa_lanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_despesa_lanca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_descricao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_nota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''label_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_data_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_data_nota As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_preencha_campos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_preencha_campos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_lanca_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_lanca_despesa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_busca_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca_despesa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_os_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_colaborador_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_colaborador_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_despesa_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_despesa_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''radio_filtro_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_status As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''radio_filtro_datas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_datas As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_calendario_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_inicial As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_calendario_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_final As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''botao_listar_despesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_listar_despesas As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''caixa_cod_relatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cod_relatorio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_buscar_relatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_buscar_relatorio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdv_despesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_despesas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''botao_realiza_pgto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_realiza_pgto As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_valor_total_sel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_valor_total_sel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_valor_total_sel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_valor_total_sel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''label_valor_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_valor_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_valor_total_despesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_valor_total_despesas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''access_rec_cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents access_rec_cliente As Global.System.Web.UI.WebControls.AccessDataSource
End Class
