'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class gerencia_notas

    '''<summary>
    '''drop_opcao_gerencia_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_opcao_gerencia_os As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''botao_opcao_gerencia_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_opcao_gerencia_nota As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_insere_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_insere_nota As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_os_lanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_lanca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_valor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_valor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_origem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_origem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_descricao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caixa_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_nota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''label_data_entrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_entrada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_data_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_data_nota As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_data_venc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_venc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_data_venc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_data_venc As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_preencha_campos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_preencha_campos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_lanca_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_lanca_nota As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_busca_notas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca_notas As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''drop_os_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_os_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drop_origem_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_origem_busca As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''radio_status_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_status_nota As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''radio_filtro_datas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_datas As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_inicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_calendario_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_inicial As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''botao_calendario_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_final As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''botao_listar_notas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_listar_notas As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''caixa_nota_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_nota_busca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''botao_buscar_nota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_buscar_nota As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdv_notas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_notas As Global.System.Web.UI.WebControls.GridView
End Class
