'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class gerencia_os
    
    '''<summary>
    '''drop_opcao_gerencia_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_opcao_gerencia_os As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''botao_opcao_gerencia_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_opcao_gerencia_os As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''painel_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_busca As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drop_rec_ano_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_rec_ano_filtro As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_rec_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_rec_os As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_rec_clientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_rec_clientes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_rec_cliente_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_rec_cliente_final As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''radio_status_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_status_os As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''buscar_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buscar_os As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_rec_dados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_rec_dados As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_excluir_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_excluir_os As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''painel_cadastra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_cadastra As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_cadast_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cadast_os As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_cadast_cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cadast_cliente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drop_cadast_cliente_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cadast_cliente_final As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''painel_engenharia0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_engenharia0 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_descricao_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_descricao_os As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_contato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_contato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''label_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_email As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''caixa_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_telefone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_usuario_abertura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_usuario_abertura As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_data_abertura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_abertura As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_calendario_aprovacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_aprovacao As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''caixa_data_limite_aprovacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_limite_aprovacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_calendario_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_final As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''caixa_data_final_projeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_data_final_projeto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_finaliza_os control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_finaliza_os As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_editar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_editar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_gravar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_cancelar_edicao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_cancelar_edicao As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''painel_engenharia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_engenharia As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_orc_eng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_orc_eng As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_proj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_proj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_proj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_proj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_proj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_proj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_plc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_plc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_plc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_plc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_plc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_plc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_ihm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_ihm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_ihm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_ihm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_ihm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_ihm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_startup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_startup As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_startup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_startup As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_startup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_startup As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''painel_ind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_ind As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_orc_ind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_orc_ind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_mont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_mont As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_mont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_mont As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_mont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_mont As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_testes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_testes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_testes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_testes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_testes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_testes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_matprima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_matprima As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''painel_inst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_inst As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_orc_inst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_orc_inst As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_mao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_mao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_horas_mao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_horas_mao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_cthora_mao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_cthora_mao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caixa_total_material control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total_material As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''painel_desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_desp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''caixa_orc_desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_orc_desp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''painel_emb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_emb As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''radio_embalagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_embalagem As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''painel_frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents painel_frete As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''radio_frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_frete As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''label_campos_obrig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_campos_obrig As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''botao_validar_dados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_validar_dados As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_cadastrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_cadastrar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''botao_infografico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_infografico As Global.System.Web.UI.WebControls.ImageButton
End Class
