'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class acompanhamento_pc

    '''<summary>
    '''panel_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''check_filtro_avancado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_filtro_avancado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drop_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drop_filtro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''caixa_filtro_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''label_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caixa_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_total As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''radio_selection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_selection As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''gdv_pc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_pc As Global.System.Web.UI.WebControls.GridView
End Class
