'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class allocated_leli
    
    '''<summary>
    '''panel_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''check_filtro_avancado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_filtro_avancado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drop_filtro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calendario_filtro_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendario_filtro_busca As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''drop_filtro2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_filtro_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_excel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''radio_filtro_datas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_filtro_datas As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''panel_dates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_dates As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''label_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_inicial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''label_data_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_inicial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''botao_calendario_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_inicial As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''label_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_final As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''label_data_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_data_final As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''botao_calendario_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_calendario_final As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
End Class
