'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class leanliftdb
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''hanel_logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hanel_logo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''panel_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_busca As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''check_filtro_avancado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_filtro_avancado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drop_filtro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drop_filtro2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_filtro2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''caixa_filtro_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caixa_filtro_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''check_items_maior_zero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_items_maior_zero As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''panel_cadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_cadastro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''label_customer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_customer1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drop_cadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drop_cadastro As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''botao_novo_cadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_novo_cadastro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
End Class
