'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class leli_items_req
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''panel_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_search As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''check_filtro_avancado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_filtro_avancado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProducts As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''texto_filtro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents texto_filtro_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_filtro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlProducts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProducts1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''texto_filtro_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents texto_filtro_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botao_sel_filtrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botao_sel_filtrado As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gdvDaDos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDaDos As Global.System.Web.UI.WebControls.GridView
End Class
